services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Web Interface (8080 wegen NPM auf Port 80)
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      # Alle Interfaces abhören (für Docker)
      DNSMASQ_LISTENING: all
      # Kein DHCP - nur DNS
      PIHOLE_DNS_: "9.9.9.9;1.1.1.1"
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    networks:
      - web-public
    # DNS-Server-Capability
    cap_add:
      - NET_ADMIN

networks:
  web-public:
    external: true
