services:
  web:
    build: .
    container_name: landing-page
    # volumes removed to rely on build copy

    networks:
      - web-public
    restart: unless-stopped

networks:
  web-public:
    external: true
